### PR TITLE
fix(docker): healthcheck and python error

### PR DESCRIPTION
**Pull request by sambacha**
fixes health check command
fixes python to force the stdout and stderr streams to be unbuffered (see logs in console) 
fixes pip to not use cache

consider: init system usage like tini

### CODE REVIEW

**Review by avsetsin — COMMENTED** [review]
@sambacha thanks for the PR, LGTM

**Comment by sambacha** [comment]
> @sambacha thanks for the PR, LGTM

Would you be open to accepting an additional PR for adding goss for smoke testing purposes? 

Thanks for the quick turnaround, much appreciated

**Comment by avsetsin** [comment]
> Would you be open to accepting an additional PR for adding goss for smoke testing purposes?
Thank you for your efforts! I'm not sure we need it since we already have a batch of smoke tests in our infra (it's a separate private repository, so I can't reference it)

**Comment by sambacha** [comment]
> > Would you be open to accepting an additional PR for adding goss for smoke testing purposes?
> 
> Thank you for your efforts! I'm not sure we need it since we already have a batch of smoke tests in our infra (it's a separate private repository, so I can't reference it)

that was what I was suspecting :) 

cheers

**Pull request merged**
